version: v2beta1
name: watcher

pipelines:
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev watcher                # 4. Start dev mode "watcher" (see "dev" section)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

images:
  watcher:
    image: watcher
    dockerfile: ./Dockerfile

deployments:
  watcher:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: watcher
            env:
              # TODO: remove dependency on env variables
              - name: TYPE
                value: webpage
              - name: ENDPOINT
                value: https://www.google.com
              - name: INTERVAL
                value: 15s
        service:
          ports:
            - port: 8081

dev:
  watcher:
    imageSelector: watcher
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.20-alpine
    sync:
      - path: ./
    terminal:
      command: ./devspace_start.sh
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    ports:
      - port: "2345"
      - port: "8081"
    open:
      - url: http://localhost:8081
    env:
      - name: TYPE
        value: webpage
      - name: ENDPOINT
        value: https://www.google.com
      - name: INTERVAL
        value: 15s

commands:
  migrate-db:
    command: |-
      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

#dependencies:
#  genie:
#   git: https://github.com/statuzproj/genie
#   branch: main
