name: release unstable image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: release unstable image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: release watcher image to quay.io
        uses: statuzproj/actions/quay-multi-arch@main
        with:
          service_name: watcher
          dockerfile_path: ./Dockerfile
          quay_registry: ${{ vars.QUAY_REGISTRY }}
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}